apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvisor-install
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gvisor-installer
  template:
    metadata:
      labels:
        app: gvisor-installer
    spec:
      initContainers:
      - name: gvisor-installer
        image: ghcr.io/coding-ia/gvisor-installer:1.0.0
        securityContext:
          privileged: true
        volumeMounts:
        - name: run-systemd
          mountPath: /run/systemd
        - name: run-dbus
          mountPath: /var/run/dbus
        - name: usr-local-bin
          mountPath: /mnt/host/usr/local/bin
        - name: host-etc
          mountPath: /mnt/host/etc
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.6
      volumes:
      - name: run-systemd
        hostPath:
          path: /run/systemd
      - name: run-dbus
        hostPath:
          path: /var/run/dbus
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: host-etc
        hostPath:
          path: /etc
---
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: gvisor
handler: runsc
